apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: databases

  source:
    repoURL: https://github.com/prathamesh8266/DOCUMENT-KNOWLEDGE-STORE.git
    targetRevision: master
    path: gitops/cloudnative-postgres/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true